// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AlterNodeConfig(arg1, arg2, arg3) {
  return window['go']['service']['Service']['AlterNodeConfig'](arg1, arg2, arg3);
}

export function AlterTopicConfig(arg1, arg2, arg3) {
  return window['go']['service']['Service']['AlterTopicConfig'](arg1, arg2, arg3);
}

export function Consumer(arg1, arg2, arg3, arg4) {
  return window['go']['service']['Service']['Consumer'](arg1, arg2, arg3, arg4);
}

export function CreatePartitions(arg1, arg2) {
  return window['go']['service']['Service']['CreatePartitions'](arg1, arg2);
}

export function CreateTopics(arg1, arg2, arg3, arg4) {
  return window['go']['service']['Service']['CreateTopics'](arg1, arg2, arg3, arg4);
}

export function DeleteGroup(arg1) {
  return window['go']['service']['Service']['DeleteGroup'](arg1);
}

export function DeleteTopic(arg1) {
  return window['go']['service']['Service']['DeleteTopic'](arg1);
}

export function GetBrokerConfig(arg1) {
  return window['go']['service']['Service']['GetBrokerConfig'](arg1);
}

export function GetBrokers() {
  return window['go']['service']['Service']['GetBrokers']();
}

export function GetGroupMembers(arg1) {
  return window['go']['service']['Service']['GetGroupMembers'](arg1);
}

export function GetGroups() {
  return window['go']['service']['Service']['GetGroups']();
}

export function GetTopicConfig(arg1) {
  return window['go']['service']['Service']['GetTopicConfig'](arg1);
}

export function GetTopicOffsets(arg1, arg2) {
  return window['go']['service']['Service']['GetTopicOffsets'](arg1, arg2);
}

export function GetTopics() {
  return window['go']['service']['Service']['GetTopics']();
}

export function Produce(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['service']['Service']['Produce'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SetConnect(arg1, arg2, arg3) {
  return window['go']['service']['Service']['SetConnect'](arg1, arg2, arg3);
}

export function TestClient(arg1, arg2) {
  return window['go']['service']['Service']['TestClient'](arg1, arg2);
}

export function ToMap(arg1) {
  return window['go']['service']['Service']['ToMap'](arg1);
}
