// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {kadm} from '../models';

export function AlterNodeConfig(arg1:number,arg2:string,arg3:string):Promise<types.ResultsResp>;

export function AlterTopicConfig(arg1:string,arg2:string,arg3:string):Promise<types.ResultsResp>;

export function Consumer(arg1:string,arg2:string,arg3:number,arg4:number):Promise<types.ResultsResp>;

export function CreatePartitions(arg1:Array<string>,arg2:number):Promise<types.ResultResp>;

export function CreateTopics(arg1:Array<string>,arg2:number,arg3:number,arg4:{[key: string]: string}):Promise<types.ResultResp>;

export function DeleteGroup(arg1:Array<string>):Promise<types.ResultResp>;

export function DeleteTopic(arg1:Array<string>):Promise<types.ResultResp>;

export function GetBrokerConfig(arg1:number):Promise<types.ResultsResp>;

export function GetBrokers():Promise<types.ResultResp>;

export function GetGroupMembers(arg1:Array<string>):Promise<types.ResultsResp>;

export function GetGroups():Promise<types.ResultsResp>;

export function GetTopicConfig(arg1:string):Promise<types.ResultsResp>;

export function GetTopicOffsets(arg1:Array<string>,arg2:string):Promise<types.ResultResp>;

export function GetTopics():Promise<types.ResultsResp>;

export function Produce(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:Array<{[key: string]: string}>):Promise<types.ResultsResp>;

export function SetConnect(arg1:string,arg2:{[key: string]: any},arg3:boolean):Promise<types.ResultResp>;

export function TestClient(arg1:string,arg2:{[key: string]: any}):Promise<types.ResultResp>;

export function ToMap(arg1:{[key: string]: {[key: number]: kadm.Offset}}):Promise<{[key: string]: {[key: number]: any}}>;
